apiVersion: v2
name: aws-events-exporter
description: A Helm chart for AWS events exporter
type: application
version: 1.0.0
appVersion: "1.0.0"
sources:
  - https://github.com/deliveryhero/aws-events-exporter
maintainers:
- name: nyambati
  email: no-reply@deliveryhero.com
