# Default values for aws-events-exporter.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

replicas: 1

image:
  repository: thomasnyambati/aws-events-exporter
  pullPolicy: IfNotPresent
  # Overrides the image tag whose default is the chart appVersion.
  tag: 1.0.0

imagePullSecrets: []
nameOverride: ""
fullnameOverride: ""
serviceAccountName: ""
podAnnotations: {}

podSecurityContext: {}

securityContext: {}

service:
  type: ClusterIP
  port: 80

resources: {}
nodeSelector: {}
tolerations: []
affinity: {}

exporter:
  port: 9090
  listenAddress: 0.0.0.0
  queueUrl: ""
env: {}
extraLabels: {}
