---
kind: pipeline
type: kubernetes
name: default

service_account_name: drone-aws-service-events-exporter

steps:
- name: publish  
  image: plugins/ecr
  settings:
    repo: dockerhub-mirror/aws-service-events-exporter
    registry: 940776968316.dkr.ecr.eu-west-1.amazonaws.com
    tags:
      - latest
      - ${DRONE_TAG}
  when:
    event: tag
    branch: master
