---
kind: pipeline
type: kubernetes
name: default

tolerations:
  - effect: NoSchedule
    key: app
    operator: Exists
node_selector:
  app: drone

service_account_name: drone-rps-system-engineering

trigger:
  event:
    - push
    - pull_request

steps:
- name: publish  
  image: plugins/ecr
  settings:
    repo: dockerhub-mirror/aws-service-events-exporter
    registry: 940776968316.dkr.ecr.eu-west-1.amazonaws.com
    tags:
      - latest
