---
kind: pipeline
type: kubernetes
name: default

service_account_name: drone-irsa-aws-service-events-exporter

trigger:
  event: pull_request

steps:
- name: publish
  image: plugins/ecr
  settings:
    repo: dockerhub-mirror/aws-service-events-exporter
    registry: 940776968316.dkr.ecr.eu-west-1.amazonaws.com
    tags:
      - 1.4.1
      # - ${DRONE_TAG}
  # when:
  #   event: tag
