apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "aws-events-exporter.fullname" . }}
  labels:
    {{- include "aws-events-exporter.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicas }}
  selector:
    matchLabels:
      {{- include "aws-events-exporter.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "aws-events-exporter.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ .Values.serviceAccountName }}
      securityContext:
        {{- toYaml .Values.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.securityContext | nindent 12 }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          env:
            name: LISTEN_ADDRESS
            value: {{ .Values.env.LISTEN_ADDRESS | quote }}
            name: PORT
            value: {{ .Values.env.PORT | quote }}
            name: QUEUE_URL
            value: {{ .Values.env.QUEUE_URL | quote }}
            name: AWS_REGION
            value: {{ .Values.env.AWS_REGION | quote }}
            name: AWS_CREDENTIALS_PATH
            value: {{ .Values.env.AWS_CREDENTIALS_PATH | quote }}
            name: AWS_PROFILE
            value: {{ .Values.env.AWS_PROFILE | quote }}
          ports:
            - name: http
              containerPort: 9090
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /metrics
              port: http
          readinessProbe:
            httpGet:
              path: /metrics
              port: http
          resources:
            {{- toYaml .Values.resources | nindent 12 }}
      {{- with .Values.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
