on: [pull_request]
name: Lint
jobs:
  build:
    name: Run gofmt
    runs-on: ubuntu-latest
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: 1.15.x
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Test
      run: GOFMT_OUTPUT=$(gofmt -d -l .); test -z "$GOFMT_OUTPUT" || (echo echo "$GOFMT_OUTPUT"; exit 1)
